# intro to numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/ahmedalanasweh/chess-board/.venv/lib/python3.9/site-packages/numpy/__init__.py'>

In [3]:
nums=[2,3,4,5]

In [4]:
nums_as_np=np.array(nums)

In [5]:
nums_as_np

array([2, 3, 4, 5])

In [6]:
type(nums_as_np)

numpy.ndarray

In [13]:
two_dim_array = np.array([[2,2,5],[3,3,6]])

In [8]:
two_dim_array 

array([[2, 2, 2],
       [3, 3, 3]])

In [9]:
two_dim_array .shape

(2, 3)

In [10]:
two_dim_array[0]

array([2, 2, 2])

In [11]:
two_dim_array[0][1]

2

In [14]:
two_dim_array[:,2]

array([5, 6])

# dealing with file

In [16]:
with open('student_scores.csv') as f:
    print(f.read())

Hours,Scores
2.5,21
5.1,47
3.2,27
8.5,75
3.5,30
1.5,20
9.2,88
5.5,60
8.3,81
2.7,25
7.7,85
5.9,62
4.5,41
3.3,42
1.1,17
8.9,95
2.5,30
1.9,24
6.1,67
7.4,69
2.7,30
4.8,54
3.8,35
6.9,76
7.8,86


In [21]:
dataset = np.genfromtxt('student_scores.csv',delimiter=',',skip_header=True)

In [22]:
dataset.shape

(25, 2)

In [23]:
dataset

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ],
       [ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ]])

In [25]:
# average number of hours spent studying

In [26]:
hours = dataset[:,0]

In [28]:
avg_studeied_hours = np.average(hours)
avg_studeied_hours

5.012

In [29]:
avg_studeied_hours = np.mean(hours)

In [30]:
avg_studeied_hours

5.012

In [32]:
avg_studeied_hours= np.median(hours)
avg_studeied_hours

4.8